apiVersion: v2
name: unifi
description: A Helm chart for UniFi Network Controller
type: application
version: 0.5.2
appVersion: 9.3.45
keywords:
  - unifi
  - networking
  - controller
  - ubiquiti
home: https://ui.com/
sources:
  - https://github.com/jacobalberty/unifi-docker
maintainers:
  - name: hannoeru
    email: me@hanlee.co
dependencies:
  - name: mongodb
    version: "16.5.40"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: mongodb.enabled
